import { Project, Certificate, TechItem } from "./types";

export const projects: Project[] = [
  {
    id: 1,
    title: "DiKantin",
    description:
      "Sebuah aplikasi web dan mobile untuk mempermudah transaksi di kantin dengan sistem pemesanan digital",
    technologies: [
      "Laravel",
      "Flutter",
      "MySQL",
      "Pusher",
      "Sanctum",
      "Bootstrap",
    ],
    image: "/next.svg",
    github: "#",
    live: "#",
    category: "web",
  },
  {
    id: 2,
    title: "S-Learn",
    description:
      "Sebuah aplikasi web dan mobile LMS untuk mendukung proses pembelajaran di Jurusan Teknologi Informasi Politeknik Negeri Jember.",
    technologies: ["Laravel", "Flutter", "MySQL", "Sanctum", "Tailwind CSS"],
    image: "/next.svg",
    github: "#",
    live: "#",
    category: "web",
  },
  {
    id: 3,
    title: "NusaGrow",
    description:
      "Sebuah aplikasi web untuk menghubungkan produsen bahan mentah dengan pelaku industri pengolah seperti UMKM dan pabrik kecil, guna mendukung hilirisasi hasil bahan mentah secara digital.",
    technologies: ["Laravel", "Flutter", "MySQL", "Sanctum", "Tailwind CSS"],
    image: "/next.svg",
    github: "#",
    live: "#",
    category: "web",
  },
  {
    id: 4,
    title: "NutriGrowth",
    description:
      "Sebuah aplikasi mobile untuk monitoring tumbuh kembang anak secara real-time",
    technologies: [
      "Laravel",
      "Flutter",
      "MySQL",
      "Tailwind CSS",
      "Sanctum",
      "Pusher",
      "HiveMq",
      "IoT",
    ],
    image: "/next.svg",
    github: "#",
    live: "#",
    category: "mobile",
  },
  {
    id: 5,
    title: "SmartGrow",
    description:
      "Sebuah aplikasi web dan mobile untuk sistem pemantauan hidroponik berbasis IoT menggunakan logika fuzzy dalam sebuah studi independen di Polije.",
    technologies: [
      "Streamlit",
      "Flutter",
      "MQTT",
      "IoT",
      "Decision Support System",
    ],
    image: "/next.svg",
    github: "#",
    live: "#",
    category: "web",
  },
  {
    id: 6,
    title: "SmartGrow",
    description:
      "Sebuah aplikasi web dan mobile untuk sistem pemantauan hidroponik berbasis IoT menggunakan logika fuzzy dalam sebuah studi independen di Polije.",
    technologies: [
      "Streamlit",
      "Flutter",
      "MQTT",
      "IoT",
      "Decision Support System",
    ],
    image: "/next.svg",
    github: "#",
    live: "#",
    category: "mobile",
  },
  {
    id: 7,
    title: "JemberSpot",
    description:
      "Sebuah aplikasi web inovatif yang dikembangkan untuk meningkatkan eksposur pariwisata di Jember. Aplikasi ini dibuat dalam rangka kompetisi yang diselenggarakan oleh UKM Linux And Open Source (LAOS) di Fakultas Ilmu Komputer, Universitas Jember,",
    technologies: ["Laravel", "Tailwind CSS"],
    image: "/next.svg",
    github: "#",
    live: "#",
    category: "web",
  },
  {
    id: 8,
    title: "EduPlay",
    description:
      "Sebuah game 2D untuk anak-anak yang dibuat untuk mengedukasi anak usia dini tentang bentuk-bentuk, hewan, angka, dan warna.",
    technologies: ["Unity"],
    image: "/next.svg",
    github: "#",
    live: "#",
    category: "web",
  },
  {
    id: 9,
    title: "Smart Air Presence System (S.M.A.R.T)",
    description:
      "Sebuah sistem otomatis untuk mengatur suhu ruangan (AC) menggunakan sensor infrared, yang dikendalikan berdasarkan jumlah orang di dalam ruangan.",
    technologies: ["Streamlit", "IoT"],
    image: "/next.svg",
    github: "#",
    live: "#",
    category: "web",
  },
  {
    id: 10,
    title: "Internify",
    description:
      "Sebuah aplikasi web dan mobile yang berfungsi sebagai sistem terpusat untuk administrasi kegiatan magang di Jurusan Teknologi Informasi Politeknik Negeri Jember. ",
    technologies: ["Laravel", "Flutter", "MySQL", "Sanctum", "Tailwind CSS"],
    image: "/next.svg",
    github: "#",
    live: "#",
    category: "mobile",
  },
  {
    id: 11,
    title: "Sistem Informasi Competition Center (SICC)",
    description:
      "Sebuah aplikasi web dan mobile yang berfungsi sebagai pusat informasi kompetisi bagi mahasiswa di Jurusan Teknologi Informasi Politeknik Negeri Jember.",
    technologies: ["Laravel", "Flutter", "MySQL", "Sanctum", "Tailwind CSS"],
    image: "/next.svg",
    github: "#",
    live: "#",
    category: "web",
  },
  {
    id: 12,
    title: "Stay Clean",
    description:
      "Sebuah aplikasi desktop untuk sistem manajemen jasa laundry yang dirancang untuk meningkatkan efisiensi operasional.",
    technologies: ["Java", "MySQL", "Barcode Scanner", "RFID"],
    image: "/next.svg",
    github: "#",
    live: "#",
    category: "mobile",
  },
  {
    id: 13,
    title: "Website Expo dan Pekan Ilmiah Mahasiswa (EPIM)",
    description:
      "Sebuah aplikasi web yang berfungsi sebagai sistem terpusat untuk administrasi kegiatan EPIM di Jurusan Teknologi Informasi Politeknik Negeri Jember.",
    technologies: ["Laravel", "MySQL", "Tailwind CSS"],
    image: "/next.svg",
    github: "#",
    live: "#",
    category: "web",
  },
  {
    id: 14,
    title: "Website Profil HMJTI Polije 2023",
    description:
      "Sebuah aplikasi web yang berfungsi sebagai informasi tentang HMJTI Polije 2023.",
    technologies: ["Laravel", "MySQL", "Tailwind CSS"],
    image: "/next.svg",
    github: "#",
    live: "#",
    category: "web",
  },
  {
    id: 15,
    title: "Rentalin",
    description:
      "Sebuah aplikasi desktop untuk mempermudah proses penyewaan alat-alat camping. ",
    technologies: ["Java", "MySQL"],
    image: "/next.svg",
    github: "#",
    live: "#",
    category: "web",
  },
];

export const techStack: TechItem[] = [
  // Frontend
  {
    name: "React",
    icon: "⚛️",
    color: "from-blue-400 to-cyan-500",
    category: "frontend",
    simpleIconsSlug: "react",
  },
  {
    name: "Next.js",
    icon: "⚡",
    color: "from-gray-600 to-gray-800",
    category: "frontend",
    simpleIconsSlug: "nextdotjs",
  },
  {
    name: "TypeScript",
    icon: "🔷",
    color: "from-blue-500 to-blue-700",
    category: "frontend",
    simpleIconsSlug: "typescript",
  },
  {
    name: "JavaScript",
    icon: "🟡",
    color: "from-yellow-400 to-yellow-600",
    category: "frontend",
    simpleIconsSlug: "javascript",
  },
  {
    name: "HTML5",
    icon: "🌐",
    color: "from-orange-500 to-red-500",
    category: "frontend",
    simpleIconsSlug: "html5",
  },
  {
    name: "CSS3",
    icon: "🎨",
    color: "from-blue-500 to-purple-600",
    category: "frontend",
    simpleIconsSlug: "css",
  },
  {
    name: "Tailwind CSS",
    icon: "💨",
    color: "from-cyan-400 to-blue-500",
    category: "frontend",
    simpleIconsSlug: "tailwindcss",
  },

  // Backend
  {
    name: "Node.js",
    icon: "🟢",
    color: "from-green-500 to-green-700",
    category: "backend",
    simpleIconsSlug: "nodedotjs",
  },
  {
    name: "Express",
    icon: "🚂",
    color: "from-gray-500 to-gray-700",
    category: "backend",
    simpleIconsSlug: "express",
  },
  {
    name: "Python",
    icon: "🐍",
    color: "from-yellow-500 to-blue-600",
    category: "backend",
    simpleIconsSlug: "python",
  },
  {
    name: "PostgreSQL",
    icon: "🐘",
    color: "from-blue-600 to-blue-800",
    category: "backend",
    simpleIconsSlug: "postgresql",
  },
  {
    name: "MongoDB",
    icon: "🍃",
    color: "from-green-400 to-green-600",
    category: "backend",
    simpleIconsSlug: "mongodb",
  },
  {
    name: "Firebase",
    icon: "🔥",
    color: "from-orange-500 to-yellow-500",
    category: "backend",
    simpleIconsSlug: "firebase",
  },
  {
    name: "Supabase",
    icon: "🦄",
    color: "from-blue-500 to-blue-700",
    category: "backend",
    simpleIconsSlug: "supabase",
  },

  // Mobile
  {
    name: "Android Development",
    icon: "🤖",
    color: "from-green-500 to-green-700",
    category: "mobile",
    simpleIconsSlug: "android",
  },
  {
    name: "Mobile UI/UX",
    icon: "📐",
    color: "from-purple-500 to-pink-500",
    category: "mobile",
  },
  {
    name: "Flutter",
    icon: "🎨",
    color: "from-blue-500 to-blue-700",
    category: "mobile",
    simpleIconsSlug: "flutter",
  },

  // Tools
  {
    name: "Git",
    icon: "📚",
    color: "from-orange-500 to-red-500",
    category: "tools",
    simpleIconsSlug: "git",
  },
  {
    name: "Vercel",
    icon: "▲",
    color: "from-black to-gray-800",
    category: "tools",
    simpleIconsSlug: "vercel",
  },
  {
    name: "Figma",
    icon: "🎨",
    color: "from-purple-500 to-pink-500",
    category: "tools",
    simpleIconsSlug: "figma",
  },
  {
    name: "Postman",
    icon: "📮",
    color: "from-orange-500 to-red-500",
    category: "tools",
    simpleIconsSlug: "postman",
  },
  {
    name: "Notion",
    icon: "📝",
    color: "from-gray-500 to-gray-700",
    category: "tools",
    simpleIconsSlug: "notion",
  },
  {
    name: "VS Code",
    icon: "🎨",
    color: "from-blue-500 to-blue-700",
    category: "tools",
    simpleIconsSlug: "visualstudiocode",
  },
  {
    name: "Apidog",
    icon: "🎨",
    color: "from-blue-500 to-blue-700",
    category: "tools",
  },
];

export const certificates: Certificate[] = [
  {
    id: 1,
    title: "AI Praktis Untuk Produktivitas",
    issuer: "Dicoding Indonesia",
    date: "May 2025 - May 2028",
    image: "/next.svg",
    link: "#",
    category: "certificates",
  },
  {
    id: 2,
    title: "Belajar Penggunaan Generative AI",
    issuer: "Dicoding Indonesia",
    date: "May 2025 - May 2028",
    image: "/next.svg",
    link: "#",
    category: "certificates",
  },
  {
    id: 3,
    title: "English Test - B2+",
    issuer: "SmallTalk2Me",
    date: "Mar 2025",
    image: "/next.svg",
    link: "#",
    category: "certificates",
  },
  {
    id: 4,
    title: "Belajar Analisis Data dengan Python",
    issuer: "Dicoding Indonesia",
    date: "Sep 2024 - Sep 2027",
    image: "/next.svg",
    link: "#",
    category: "certificates",
  },
  {
    id: 5,
    title: "Belajar Dasar SQL",
    issuer: "Dicoding Indonesia",
    date: "Aug 2024 - Aug 2027",
    image: "/next.svg",
    link: "#",
    category: "certificates",
  },
  {
    id: 6,
    title: "Belajar Dasar Visualisasi Data",
    issuer: "Dicoding Indonesia",
    date: "Aug 2024 - aug 2027",
    image: "/next.svg",
    link: "#",
    category: "certificates",
  },
  {
    id: 7,
    title: "Memulai Pemrograman dengan Python",
    issuer: "Dicoding Indonesia",
    date: "Aug 2024 - aug 2027",
    image: "/next.svg",
    link: "#",
    category: "certificates",
  },
  {
    id: 8,
    title: "Belajar Dasar AI",
    issuer: "Dicoding Indonesia",
    date: "Jul 2024 - Jul 2027",
    image: "/next.svg",
    link: "#",
    category: "certificates",
  },
  {
    id: 9,
    title: "Memulai Pemrograman dengan Java",
    issuer: "Dicoding Indonesia",
    date: "Jul 2024 - Jul 2027",
    image: "/next.svg",
    link: "#",
    category: "certificates",
  },
  {
    id: 10,
    title: "IoT - Software and Platforms (Gold)",
    issuer: "Skilvul",
    date: "May 2024 - May 2026",
    image: "/next.svg",
    link: "#",
    category: "certificates",
  },
  {
    id: 11,
    title: "IoT Development with ESP32 (Gold)",
    issuer: "Skilvul",
    date: "May 2024 - May 2026",
    image: "/next.svg",
    link: "#",
    category: "certificates",
  },
  {
    id: 12,
    title: "IoT Fundamentals (Gold)",
    issuer: "Skilvul",
    date: "Apr 2024 - Apr 2026",
    image: "/next.svg",
    link: "#",
    category: "certificates",
  },
  {
    id: 13,
    title: "Python Lanjutan (Gold)",
    issuer: "Skilvul",
    date: "Mar 2024 - Mar 2026",
    image: "/next.svg",
    link: "#",
    category: "certificates",
  },
  {
    id: 14,
    title: "Algorithm & Data Structure with Python (Gold)",
    issuer: "Skilvul",
    date: "Mar 2024 - Mar 2026",
    image: "/next.svg",
    link: "#",
    category: "certificates",
  },
  {
    id: 15,
    title: "Python Dasar (Gold)",
    issuer: "Skilvul",
    date: "Mar 2024 - Mar 2026",
    image: "/next.svg",
    link: "#",
    category: "certificates",
  },
  {
    id: 16,
    title: "KKNI Level II pada Kompetensi Keahlian Rekayasa Perangkat Lunak",
    issuer: "BNSP",
    date: "Jun 2022 - Jun 2025",
    image: "/next.svg",
    link: "#",
    category: "certificates",
  },
  {
    id: 17,
    title: "2nd Winner of National Web Design Competition - UCDC 2025",
    issuer: "UKM Cyber AMIKOM Surakarta",
    date: "Jun 2025",
    image: "/next.svg",
    link: "#",
    category: "achievements",
  },
  {
    id: 18,
    title: "Finalist - Hackfest 2025",
    issuer: "Universitas Ciputra Surabaya",
    date: "Apr 2025",
    image: "/next.svg",
    link: "#",
    category: "achievements",
  },
  {
    id: 19,
    title:
      "1st Winner of Innovation Category for Creating Shared Value (Stunting Reduction) - 5th Innovillage 2024",
    issuer: "Telkom Indonesia & Telkom University",
    date: "Dec 2024",
    image: "/next.svg",
    link: "#",
    category: "achievements",
  },
  {
    id: 20,
    title: "Finalist - Citech 2024",
    issuer: "UKM Linux and Open Source (LAOS), Fasilkom, Universitas Jember",
    date: "Oct 2024",
    image: "/next.svg",
    link: "#",
    category: "achievements",
  },
  {
    id: 21,
    title: "Top 40 Student Teams - Samsung Innovation Campus Batch 5",
    issuer: "Samsung",
    date: "Sep 2024",
    image: "/next.svg",
    link: "#",
    category: "achievements",
  },
  {
    id: 22,
    title: "3rd Winner of Best Application - TIF Exhibition 2023",
    issuer: "Jurusan Teknologi Informasi Politeknik Negeri Jember",
    date: "Dec 2023",
    image: "/next.svg",
    link: "#",
    category: "achievements",
  },
];
